### ISSUE TITLE
Splitting of TypeDefs in different files than index.js?

### ISSUE THREAD

**Issue by agustif** [apollographql/movie-database-graphql#4]
Should I find the best strategy to not have a monstrous index.js file, or is it preferred for some performance stuff since this is a wrapper after all?

**Comment by stubailo** [comment]
I think splitting files is great! We have some ideas here: https://www.apollographql.com/docs/graphql-tools/generate-schema.html#modularizing

There is no performance drawback to using many files and any production API will have way more code than can fit in one file!
