### ISSUE TITLE
Schema stitching or store rehydratation to load more data from relations

### ISSUE THREAD

**Issue by agustif** [apollographql/movie-database-graphql#6]
some stuff is only partially put out in relations, like id + name, but not the rest of the fields available by doing an extra request to movies/id/extra_fields (as an append_to_response=)

**Comment by stubailo** [comment]
Yeah, this was meant to be just a minimal example for a particular demo, but I think it would be great for you to have a more advanced version of the app we can link to! Let's talk in #2
