### ISSUE TITLE
Live API hosted link is broken.

### ISSUE THREAD

**Issue by pankaja92** [apollographql/movie-database-graphql#7]
In the documentation it says **Check out the live API hosted on Heroku.** . But the link is not working

**Comment by agustif** [comment]
I thought so, too, BUT it's just the README link. the link on the description is working.

here: https://movie-database-graphql.herokuapp.com/graphiql

I also forked/deployed it to now, in case you're interested, also added some more endpoints and shit
https://github.com/agustif/movie-database-graphql

**Comment by stubailo** [comment]
Thank you! I just renamed it and forgot to update the README :]
